# Generated by Django 5.2.5 on 2025-09-01 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_full_name_user_name_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carownerprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
