# Generated by Django 5.2.5 on 2025-09-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_carownerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('car_owner', 'Car Owner'), ('repair_shop', 'Repair Shop'), ('insurances_provider', 'Insurance Provider'), ('repair_shop_employee', 'Repair Shop Employee')], max_length=100),
        ),
    ]
