# Generated by Django 5.2.5 on 2025-09-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_image_repairshopprofile_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carownerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_owner_profile_image'),
        ),
    ]
