# Generated by Django 5.2.5 on 2025-09-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_carownerprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carownerprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='car_owner_profile_image'),
        ),
    ]
