# Generated by Django 5.2.5 on 2025-09-01 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageAnalyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('car_model', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/analyzes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_estimated_min', models.CharField(blank=True, max_length=100, null=True)),
                ('total_estimated_max', models.CharField(blank=True, max_length=100, null=True)),
                ('severity', models.CharField(blank=True, max_length=50, null=True)),
                ('car_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(blank=True, max_length=100, null=True)),
                ('damage_type', models.CharField(blank=True, max_length=100, null=True)),
                ('damage', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('estimated_cost_min', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_cost_max', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='damage_analyze.damageanalyze')),
            ],
        ),
        migrations.CreateModel(
            name='HumanAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humans', to='damage_analyze.damageanalyze')),
            ],
        ),
    ]
